### ISSUE TITLE
Add new dataset for clustering problems inside datasets folder

### ISSUE THREAD

**Issue by sagnik1511** [sagnik1511/Tabular-AutoML#25]
Add a new tabular dataset for clustering problems inside `tab_automl/datasets` and also add the dataset class inside `tab_automl/automl/datasets.py`.

Add proper comments and quality in code.

Follow contributing guidelines on [README.md](https://github.com/sagnik1511/Tabular-AutoML/blob/main/README.md)

**Comment by Tihsrah** [comment]
I would like to work on this issue.

**Comment by sagnik1511** [comment]
Good Luck, Assigned!!!

**Comment by sagnik1511** [comment]
Is your work completed? @Tihsrah , the expected time has been over.

**Comment by snega16** [comment]
I want to work on this issue under JWOC.

**Comment by sagnik1511** [comment]
Unassigning @Tihsrah

**Comment by sagnik1511** [comment]
@snega16, Good Luck, assigned!

**Comment by sagnik1511** [comment]
@snega16, Good Work!
