### ISSUE TITLE
Update every print statements to f-string

### ISSUE THREAD

**Issue by sagnik1511** [sagnik1511/Tabular-AutoML#3]
Update all the print statements will f strings for a **single** file.

Example:

```python
>>> my_name = "Sagnik"
>>> # Not updated
>>> print("Hi, my name is ",my_name)
>>> # Process 1
>>> print("Hi, my name is {}".format(my_name))
>>> # Process 2
>>> print(f"Hi, my name is {my_name}")
>>> # The print statement may not have any variables, still you have to update those.
>>> print("Good Morning!")
>>> # Updated f-string
>>> print(f"Good Morning!")
```

Follow contributing guidelines on [README.md](https://github.com/sagnik1511/Tabular-AutoML/blob/main/README.md)

**Comment by Aadityajoshi151** [comment]
Hello
I would like to work on this issue.
Can you please tell in which file changes are to be made?

**Comment by sagnik1511** [comment]
@Aadityajoshi151, This repo is currently under JWOC, so if you want to contribute to this please make sure you're registered for the event and also the contributions will be starting on 1st Feb. Visit https://jwoc.tech to register.

**Comment by RishiKumarRay** [comment]
I would like to try , can you assign

**Comment by sagnik1511** [comment]
This repo is currently under [JGEC Winter of code](https://jwoc.tech). If one wants to contribute to the issues, you have to register yourself in the program. And one more thing, the contribution will start from 1st February. Register here https://jwoc.tech

**Comment by ashubhamg** [comment]
I would like to try, can you assign?

**Comment by sagnik1511** [comment]
> I would like to try, can you assign?

https://github.com/sagnik1511/Tabular-AutoML/issues/3#issuecomment-1014306610

**Comment by PranK14** [comment]
i would like to work on this as my first issue

**Comment by PurnaChandraMansingh** [comment]
I have registered for JGEC Winter of code, can I work on this ?

**Comment by Tihsrah** [comment]
I would like to work on this as my first issue.

**Comment by sagnik1511** [comment]
@PurnaChandraMansingh @PranK14 @Tihsrah 
Please Note : all the comments before 1st feb are invalid as the coding period starts on 1st feb.

**Comment by kunalchhabra37** [comment]
I want to contribute on this issue under JWOC.
@sagnik1511

**Comment by Adi9235** [comment]
I want to work on this issue under JWOC

**Comment by VishnuBhaarath** [comment]
I want to work on this issue under @JWOC

**Comment by PranK14** [comment]
i want to work on this issue @jwoc

**Comment by mithil-sri-sai** [comment]
I want to work on this issue under JWOC

**Comment by sagnik1511** [comment]
@kunalchhabra37, Good Luck! Assigned!

**Comment by sagnik1511** [comment]
> I want to work on this issue under JWOC

Hi @Adi9235, if there's any print statement is left undone with the f-string format, please paste it here. If found please update and create a PR. If you want to get assigned, please comment with your confirmation.

**Comment by Adi9235** [comment]
Sure i will look if any is left @sagnik1511

**Comment by Adi9235** [comment]
@sagnik1511 i have found some without f statement in training,py of automl and other  files also so I can correct it

**Comment by sagnik1511** [comment]
Please, share the permalinks here for me to check.

**Comment by Adi9235** [comment]
https://github.com/sagnik1511/Tabular-AutoML/blob/2b8fda734fc614a37f776ad07350892589ba380e/tab_automl/automl/datasets.py

in this  check line number 84 @sagnik1511

**Comment by sagnik1511** [comment]
Thanks for finding it. The best approach will be to wait for some more commits, if the count of these statements crosses 5, I'll assign you.

**Comment by ayushmorbar** [comment]
I would like to work on this issue as a JWoC mentee.

**Comment by ayushmorbar** [comment]
I would like to work on this issue under JWoC

**Comment by ayushmorbar** [comment]
Hey, assign me this **issue #3**, I would like to work on this under JGEC JWoC !!!

**Comment by Sherlock-221BBS** [comment]
I have assigned you the issue, solve the issue within your respective time
limit
