### ISSUE TITLE
Load data from different file formats.

### ISSUE THREAD

**Issue by sagnik1511** [sagnik1511/Tabular-AutoML#4]
The datasets are getting loaded on `.csv` format only in the codebase, example : [see here](https://github.com/sagnik1511/Tabular-AutoML/blob/94baa1ecedb9b85cd3a8cf43e7d336b76a3e8cd2/tab_automl/automl/datasets.py#L15).

Add different data loading techniques for other formats like `.txt` , `.sqlite`, etc.
Add required comments in the code.

Follow contributing guidelines on [README.md](https://github.com/sagnik1511/Tabular-AutoML/blob/main/README.md)

**Comment by Tihsrah** [comment]
I want to work on this issue under JWOC

**Comment by sagnik1511** [comment]
Good Luck! Assigned.
