### ISSUE TITLE
Add contributors section

### ISSUE THREAD

**Issue by khushimarothi** [sagnik1511/Tabular-AutoML#44]
want to add contributors section in readme

**Comment by sagnik1511** [comment]
That is merely a contribution! If you want to update README, update the new functionalities added in JWOC-2023. Rename the Issue, if it looks/sounds correct, I'll add the JWOC label to it so that you can start working. Nevertheless, happy contributing !!!

**Comment by khushimarothi** [comment]
I just saw there are 8 contributors in this repo. They will be showcased under the contributors section
