### ISSUE TITLE
Add new models for regression training

### ISSUE THREAD

**Issue by sagnik1511** [sagnik1511/Tabular-AutoML#6]
1. Add new regression models on single_model_dict which is in [here](https://github.com/sagnik1511/Tabular-AutoML/blob/46e385dcc5fe8a67b4f87861cb7ad3b84d8420d6/tab_automl/automl/models.py#L10).
2. Update the requirements if the library of the new model is missing from it.
3. Add reasons why those models are added to the PR.

Follow contributing guidelines on [README.md](https://github.com/sagnik1511/Tabular-AutoML/blob/main/README.md)

**Comment by snega16** [comment]
I wish to work on this issue. Please assign this to me.

**Comment by snega16** [comment]
I want to work on this issue under JWOC

**Comment by VishnuBhaarath** [comment]
I want to work on this issue under JWOC

**Comment by sagnik1511** [comment]
Good Luck! Assigned!

**Comment by sagnik1511** [comment]
Thanks @snega16 , merged. Look for other issues or create if you any ideas.

**Comment by sagnik1511** [comment]
@VishnuBhaarath , if you want to contribute here, drop a confirmation, I'll assign you.

**Comment by VishnuBhaarath** [comment]
> @VishnuBhaarath , if you want to contribute here, drop a confirmation, I'll assign you.

yeah thanks will do

**Comment by PalaVenkiReddy** [comment]
I wanted to work on this issue under JWOC.

**Comment by Sherlock-221BBS** [comment]
I have assigned you the issue, go ahead and work on it
